import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import sharp from 'sharp';

test('fixed artwork defaults, live customisation, patterns, save and reset', async ({ page }) => {
  await page.goto('/admin/research/note-02/');
  const preview = page.locator('aside .research-art');
  await page.getByRole('button',{ name:'Theme artwork',exact:true }).click();
  await expect(page.getByRole('button', { name: /Choose .* artwork/ })).toHaveCount(13);
  await page.getByRole('button', { name: 'Choose Orbits artwork', exact:true }).click();
  await expect(page.getByLabel('Cover word', { exact:true })).toHaveValue('Orbits');
  const geometry = await preview.locator('svg').innerHTML();
  await page.getByLabel('Cover word', { exact:true }).fill('Energy');
  await page.getByLabel('Cover colour', { exact:true }).fill('#123456');
  await expect(preview).toHaveAttribute('data-cover-word','Energy'); await expect(preview).toHaveCSS('background-color','rgb(18, 52, 86)');
  expect(await preview.locator('svg').innerHTML()).toBe(geometry);
  await page.getByRole('button', { name:'Save changes',exact:true }).click(); await expect(page.getByRole('status')).toContainText('Saved to');
  await page.reload(); await expect(preview).toHaveAttribute('data-cover-preset','orbits'); await expect(page.getByLabel('Cover word',{ exact:true })).toHaveValue('Energy');
  await page.getByRole('button',{ name:'Hero Patterns',exact:true }).click();
  await expect(page.getByRole('button',{ name:/Choose .* pattern/ })).toHaveCount(87);
  await page.getByLabel('Find a pattern').fill('wallpaper');
  await expect(page.getByRole('button',{ name:'Choose Wallpaper pattern',exact:true })).toBeVisible();
  await page.getByLabel('Find a pattern').fill('hexagon');
  await page.getByRole('button',{ name:/Choose .* pattern/ }).first().click();
  await expect(preview).toHaveAttribute('data-cover-type','hero');
  await expect(page.getByLabel('Foreground colour',{ exact:true })).toHaveValue('#000000');
  await expect(page.getByLabel('Foreground opacity',{ exact:true })).toHaveValue('0.4');
  await page.getByLabel('Cover word',{ exact:true }).fill('Banking');
  await page.getByLabel('Foreground colour',{ exact:true }).fill('#7141a6');
  await page.getByLabel('Background colour',{ exact:true }).fill('#e4daef');
  await page.getByLabel('Foreground opacity',{ exact:true }).fill('0.73');
  await expect(preview.locator('.hero-pattern-layer')).toHaveCSS('opacity','0.73');
  await expect(preview.locator('.hero-pattern-layer')).toHaveAttribute('data-pattern-foreground','#7141a6');
  await expect(preview).toHaveAttribute('data-cover-word','Banking');
  const bg = await preview.locator('.hero-pattern-layer').evaluate(el => getComputedStyle(el).backgroundImage);
  expect(bg).toContain('data:image/svg+xml');
  await page.getByRole('button',{ name:'Save changes',exact:true }).click(); await expect(page.getByRole('status')).toContainText('Saved to');
  await page.reload(); await expect(preview).toHaveAttribute('data-cover-type','hero'); await expect(page.getByLabel('Background colour',{ exact:true })).toHaveValue('#e4daef');
  await expect(page.getByLabel('Foreground colour',{ exact:true })).toHaveValue('#7141a6');
  await expect(page.getByLabel('Foreground opacity',{ exact:true })).toHaveValue('0.73');
  await page.getByRole('button',{ name:'Theme artwork',exact:true }).click(); await page.getByRole('button',{ name:'Choose Foundations artwork',exact:true }).click();
  page.once('dialog',d => d.accept()); await page.getByRole('button',{ name:'Reset edits',exact:true }).click(); await expect(preview).toHaveAttribute('data-cover-type','hero');
  await expect(preview.locator('.hero-pattern-layer')).toHaveCSS('opacity','0.73');
  for (const width of [320,390,768,1440]) { await page.setViewportSize({ width,height:1000 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth+1)).toBe(true); }
  expect((await new AxeBuilder({ page }).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations).toEqual([]);
  await page.goto('/research/the-assumptions-underneath/'); await expect(page.locator('main .research-art')).toHaveAttribute('data-cover-word','Banking');
  await expect(page.locator('main .hero-pattern-layer')).toHaveCSS('opacity','0.73');
  await expect(page.locator('main .hero-pattern-layer')).toHaveAttribute('data-pattern-foreground','#7141a6');
});

test('import, crop, customise, re-crop, cancel, failure recovery and persist images', async ({ page,request }, info) => {
  const errors: string[] = []; page.on('pageerror',e => errors.push(e.message));
  await page.goto('/admin/research/note-03/');
  const preview = page.locator('aside .research-art');
  await page.getByRole('button',{ name:'Theme artwork',exact:true }).click();
  await page.getByRole('button',{ name:'Choose Foundations artwork',exact:true }).click();
  await page.getByRole('button',{ name:'Import image',exact:true }).click();
  const bytes = await sharp({ create:{ width:1000,height:800,channels:3,background:'#468a79' } }).png().toBuffer();
  await page.getByLabel('Import cover image').setInputFiles({ name:'Photo.png',mimeType:'image/png',buffer:bytes });
  const dialog = page.getByRole('dialog'); await expect(dialog).toBeVisible();
  await expect(dialog.locator('img')).toHaveJSProperty('naturalWidth',1000);
  await dialog.getByLabel('Crop zoom').fill('2');
  const frame = await dialog.locator('img').locator('..').boundingBox();
  await page.mouse.move(frame!.x + frame!.width / 2, frame!.y + frame!.height / 2);
  await page.mouse.down(); await page.mouse.move(frame!.x + frame!.width / 2 + 20, frame!.y + frame!.height / 2 + 10); await page.mouse.up();
  expect(Number(await dialog.getByLabel('Crop horizontal position').inputValue())).toBeLessThan(0.5);
  await dialog.getByLabel('Crop horizontal position').fill('0.2');
  await dialog.getByLabel('Crop vertical position').fill('0.7');
  // Keyboard controls and focus stay within the modal.
  await dialog.getByLabel('Crop zoom').focus(); await page.keyboard.press('ArrowRight');
  expect(Number(await dialog.getByLabel('Crop zoom').inputValue())).toBeGreaterThan(2);
  expect((await new AxeBuilder({ page }).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations).toEqual([]);
  await page.screenshot({ path:`/private/tmp/artwork-crop-${info.project.name}.png` });
  await dialog.getByRole('button',{ name:'Use this crop',exact:true }).click(); await expect(dialog).not.toBeVisible();
  await expect(preview).toHaveAttribute('data-cover-type','image'); await expect(page.getByLabel('Cover word',{ exact:true })).toHaveValue('Image');
  await expect(preview.locator('img')).toHaveJSProperty('naturalWidth',497);
  const firstId = await preview.getAttribute('data-cover-image');
  await page.getByLabel('Cover word',{ exact:true }).fill('Markets'); await page.getByLabel('Cover colour',{ exact:true }).fill('#f7ecd5');
  await page.getByRole('button',{ name:'Save changes',exact:true }).click(); await expect(page.getByRole('status')).toContainText('Saved to');
  await page.reload(); await expect(preview).toHaveAttribute('data-cover-image',firstId!); await expect(page.getByLabel('Cover word',{ exact:true })).toHaveValue('Markets');
  await page.getByRole('button',{ name:'Adjust image crop',exact:true }).click(); await expect(dialog).toBeVisible();
  await expect(dialog.getByLabel('Crop zoom')).toHaveValue('2.01');
  await dialog.getByRole('button',{ name:'Reset crop',exact:true }).click(); await expect(dialog.getByLabel('Crop zoom')).toHaveValue('1');
  await dialog.getByRole('button',{ name:'Cancel',exact:true }).click(); await expect(preview).toHaveAttribute('data-cover-image',firstId!);
  await page.getByRole('button',{ name:'Adjust image crop',exact:true }).click();
  await page.route('**/admin/api/images/',route => route.abort());
  await dialog.getByRole('button',{ name:'Use this crop',exact:true }).click(); await expect(dialog.getByRole('alert')).toBeVisible(); await expect(dialog.getByRole('button',{ name:'Cancel',exact:true })).toBeEnabled();
  await page.unroute('**/admin/api/images/'); await dialog.getByRole('button',{ name:'Use this crop',exact:true }).click(); await expect(dialog).not.toBeVisible();
  const newId = await preview.getAttribute('data-cover-image'); expect(newId).not.toBe(firstId);
  await page.getByRole('button',{ name:'Save changes',exact:true }).click(); await expect(page.getByRole('status')).toContainText('Saved to');
  const editURL=page.url(); await page.getByRole('link',{ name:'Preview',exact:true }).click(); await expect(page).toHaveURL(/\/preview\/$/);
  await expect(page.locator('.article-page .research-art')).toHaveAttribute('data-cover-image',newId!);
  await expect(page.locator('.article-page .cover-image')).toHaveJSProperty('naturalWidth',497);
  await page.goto(editURL); await page.getByRole('button',{ name:'Import image',exact:true }).click();
  await page.getByLabel('Import cover image').setInputFiles({ name:'Unsafe.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg/>') }); await expect(page.locator('main [role=alert]')).toContainText('JPEG, PNG or WebP');
  const hostile=await request.post('/admin/api/images/',{ headers:{ Origin:'https://attacker.test' },multipart:{ file:{ name:'Photo.png',mimeType:'image/png',buffer:bytes },crop:JSON.stringify({ x:.5,y:.5,zoom:1 }) } }); expect(hostile.status()).toBe(403);
  expect((await request.get(`/admin/api/images/${newId}/`,{ headers:{ 'Sec-Fetch-Site':'cross-site' } })).status()).toBe(403);
  for (const width of [320,390,1440]) { await page.setViewportSize({ width,height:1000 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth+1)).toBe(true); }
  await page.screenshot({ path:`/private/tmp/artwork-image-${info.project.name}.png`,fullPage:true });
  expect(errors).toEqual([]);
});
