import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import sharp from 'sharp';

test('About and Contact settings save, render, reset and validate the email', async ({ page }, info) => {
  await page.goto('/admin/profile/');
  const heading = await page.getByLabel('About heading', { exact: true }).inputValue();
  const biography = await page.getByLabel('Biography', { exact: true }).inputValue();
  const contact = await page.getByLabel('Contact introduction', { exact: true }).inputValue();
  const email = await page.getByLabel('Contact email', { exact: false }).inputValue();
  const emailLabel = await page.getByLabel('Email link label', { exact: true }).inputValue();
  const subject = await page.getByLabel('Email subject', { exact: true }).inputValue();
  await page.getByLabel('Contact email', { exact: false }).fill('invalid');
  await page.getByRole('button', { name: 'Save profile', exact: true }).click();
  await expect(page.locator('main [role=alert]')).toContainText('Email');
  await page.getByLabel('About heading', { exact: true }).fill(`Behind the research ${info.project.name}`);
  await page.getByLabel('Biography', { exact: true }).fill('My research story.\n\nThe questions I follow.');
  await page.getByLabel('Contact introduction', { exact: true }).fill('Send me a research question.');
  await page.getByLabel('Contact email', { exact: false }).fill('research@example.com');
  await page.getByLabel('Email link label', { exact: true }).fill('Ask a question');
  await page.getByLabel('Email subject', { exact: true }).fill('Evidence & ideas');
  await page.getByRole('button', { name: 'Save profile', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Saved to');
  await page.reload(); await expect(page.getByLabel('About heading', { exact: true })).toHaveValue(`Behind the research ${info.project.name}`);
  await page.getByLabel('About heading', { exact: true }).fill('Unsaved change');
  page.once('dialog', d => d.accept()); await page.getByRole('button', { name: 'Reset edits', exact: true }).click();
  await expect(page.getByLabel('About heading', { exact: true })).toHaveValue(`Behind the research ${info.project.name}`);
  await page.goto('/');
  await expect(page.locator('#about-title')).toContainText(`Behind the research ${info.project.name}`);
  await expect(page.getByText('My research story.', { exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Ask a question', exact: true })).toHaveAttribute('href', 'mailto:research@example.com?subject=Evidence%20%26%20ideas');
  await page.goto('/admin/profile/');
  await page.getByLabel('About heading', { exact: true }).fill(heading);
  await page.getByLabel('Biography', { exact: true }).fill(biography);
  await page.getByLabel('Contact introduction', { exact: true }).fill(contact);
  await page.getByLabel('Contact email', { exact: false }).fill(email);
  await page.getByLabel('Email link label', { exact: true }).fill(emailLabel);
  await page.getByLabel('Email subject', { exact: true }).fill(subject);
  await page.getByRole('button', { name: 'Save profile', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Saved to');
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()).violations).toEqual([]);
});

test('formatted research, lettered lists and inline images persist, crop, render and reset', async ({ page }, info) => {
  page.setDefaultTimeout(15000);
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/admin/research/new/');
  await page.getByLabel('Title', { exact: true }).fill(`Formatted research ${info.project.name}`);
  await page.getByLabel('URL slug', { exact: true }).fill(`formatted-${info.project.name}`);
  await page.getByLabel('Summary', { exact: true }).fill('A formatting and image integration test.');
  await page.getByLabel('Category', { exact: true }).fill('Research');
  await page.getByLabel('Guiding question', { exact: true }).fill('Can a richer note stay readable?');
  await page.getByLabel('Heading', { exact: true }).fill('The evidence');
  const editor = page.getByRole('textbox', { name: 'Paragraphs', exact: true });
  const toolbar = page.getByRole('group', { name: 'Paragraphs formatting', exact: true });
  await editor.fill('A formatted thought.');
  await editor.focus(); await expect(editor).toBeFocused();
  await editor.press(process.platform === 'darwin' ? 'Meta+a' : 'Control+a');
  await toolbar.getByRole('button', { name: 'Bold', exact: true }).click();
  await toolbar.getByRole('button', { name: 'Italic', exact: true }).click();
  await expect(editor.locator('strong')).toContainText('A formatted thought.');
  await expect(editor.locator('em')).toContainText('A formatted thought.');
  await toolbar.getByRole('button', { name: 'Link', exact: true }).click();
  await page.getByLabel('Link address', { exact: true }).fill('https://example.com/evidence');
  await page.getByRole('button', { name: 'Apply link', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Edit text link', exact: true })).toHaveCount(0);
  await expect(editor).toBeFocused();
  await expect(editor.locator('a')).toHaveAttribute('href', 'https://example.com/evidence');
  await editor.press('ArrowRight'); await editor.press('End');
  // Native dialog focus and WebKit selection updates complete asynchronously.
  // Confirm a caret before Enter/type so we cannot replace the selected link text.
  await expect.poll(() => editor.evaluate(element => {
    const instance = (element as HTMLElement & { editor: { state: { selection: { empty: boolean } } } }).editor;
    const selection = window.getSelection();
    return instance.state.selection.empty && selection?.isCollapsed && element.contains(selection.anchorNode);
  })).toBe(true);
  await editor.press('Enter');
  if (await toolbar.getByRole('button', { name: 'Bold', exact: true }).getAttribute('aria-pressed') === 'true') await toolbar.getByRole('button', { name: 'Bold', exact: true }).click();
  if (await toolbar.getByRole('button', { name: 'Italic', exact: true }).getAttribute('aria-pressed') === 'true') await toolbar.getByRole('button', { name: 'Italic', exact: true }).click();
  await editor.pressSequentially('A useful point');
  await expect(editor.locator('strong')).toContainText('A formatted thought.');
  await toolbar.getByRole('button', { name: 'Bullets', exact: true }).click(); await expect(editor.locator('ul')).toHaveCount(1);
  await toolbar.getByRole('button', { name: '1, 2, 3', exact: true }).click(); await expect(editor.locator('ol')).toHaveCSS('list-style-type', 'decimal');
  await toolbar.getByRole('button', { name: 'a, b, c', exact: true }).click(); await expect(editor.locator('ol')).toHaveAttribute('type', 'a');
  await editor.press('End'); await editor.press('Enter'); await editor.press('Enter');
  await editor.pressSequentially('A deeper question');
  await toolbar.getByRole('button', { name: 'Subheading', exact: true }).click(); await expect(editor.locator('h3')).toContainText('A deeper question');
  await editor.press('End'); await editor.press('Enter'); await editor.pressSequentially('An image inside this paragraph: ');
  const png = await sharp({ create: { width: 200, height: 400, channels: 3, background: '#395f52' } }).png().toBuffer();
  await page.getByLabel('Image alternative text', { exact: true }).fill('A portrait chart example');
  await page.getByLabel('Image caption (optional)', { exact: true }).fill('Evidence illustration');
  await page.getByLabel('Import article image', { exact: true }).setInputFiles({ name: 'chart.png', mimeType: 'image/png', buffer: png });
  const image = editor.getByAltText('A portrait chart example'); await expect(image).toBeVisible();
  await expect(image).toHaveAttribute('height', '400');
  await image.click(); await page.getByRole('combobox', { name: 'Image width', exact: true }).selectOption('50');
  await page.getByRole('button', { name: 'Crop selected image', exact: true }).click();
  await page.getByRole('combobox', { name: 'Crop shape', exact: true }).selectOption('1');
  await page.getByRole('button', { name: 'Use this crop', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0); await expect(image).toHaveAttribute('height', '200'); await expect(editor.locator('.editor-article-image')).toHaveAttribute('style', /width: 50%/);
  await expect(page.getByLabel('Title', { exact: true })).toHaveValue(`Formatted research ${info.project.name}`);
  await page.getByRole('button', { name: 'Create note', exact: true }).click();
  await expect(page).toHaveURL(/\/admin\/research\/note-\d+\/$/);
  const editUrl = page.url();
  await page.reload();
  await expect(editor.locator('strong')).toContainText('A formatted thought.'); await expect(editor.locator('ol')).toHaveAttribute('type', 'a');
  await expect(image).toHaveAttribute('alt', 'A portrait chart example');
  await editor.fill('An unsaved replacement');
  page.once('dialog', d => d.accept()); await page.getByRole('button', { name: 'Reset edits', exact: true }).click();
  await expect(image).toBeVisible(); await expect(editor.locator('h3')).toContainText('A deeper question');
  for (const width of [320, 390, 1440]) { await page.setViewportSize({ width, height: 900 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true); }
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()).violations).toEqual([]);
  await page.getByRole('link', { name: 'Preview', exact: true }).click();
  await expect(page.locator('.article-body strong')).toContainText('A formatted thought.');
  await expect(page.locator('.article-body ol')).toHaveAttribute('type', 'a');
  await expect(page.getByRole('heading', { name: 'A deeper question', exact: true })).toBeVisible();
  await expect(page.getByAltText('A portrait chart example')).toBeVisible();
  await expect(page.getByText('Evidence illustration', { exact: true })).toBeVisible();
  expect(await page.getByAltText('A portrait chart example').evaluate(img => (img as HTMLImageElement).naturalWidth)).toBe(200);
  await page.goto(editUrl); page.once('dialog', d => d.accept()); await page.getByRole('button', { name: 'Remove', exact: true }).click();
  expect(errors).toEqual([]);
});
