import { noteNumber } from "@/lib/research-order";
import { RichContent } from "./RichContent";
import { ResearchAttachments } from "./ResearchAttachments";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, ArrowDown, Clock3 } from "lucide-react";
import type { Research } from "@/lib/content-schema";
import { formatDate, readingTime } from "@/lib/content";
import { ResearchArt } from "./ResearchArt";
export function ResearchArticle({ note, next, back, notice, number = 1 }: { number?: number; note: Research; next?: Research; back: { href: string; label: string }; notice?: React.ReactNode }) {
  return <main className="wrap article-page" id="main"><Link className="text-link back-link" href={back.href}><ArrowLeft size={17} aria-hidden="true" /> {back.label}</Link>{notice}<header className="article-heading"><span className="eyebrow">{note.category}</span><h1 id="top" tabIndex={-1}>{note.title}<span className="green-period">.</span></h1><p>{note.summary}</p><div className="article-meta"><span>{note.status === "sample" ? "Example note" : formatDate(note.publishedAt)}</span><span aria-hidden="true">/</span><span><Clock3 size={14} aria-hidden="true" /> {readingTime(note)} min read</span></div></header><ResearchArt theme={note.theme} cover={note.cover} large number={noteNumber(note, number)} />
    <ResearchAttachments attachments={note.attachments} />
    <div className="article-layout"><aside className="article-aside"><span className="eyebrow">IN THIS NOTE</span><nav aria-label="On this page">{note.sections.map((section, index) => <a key={section.heading} href={`#section-${index + 1}`}><span>{String(index + 1).padStart(2, "0")}</span>{section.heading}</a>)}</nav><div className="article-tags">{note.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></aside><article className="article-body">{note.status === "sample" && <p className="sample-note">Illustrative research exercise. This example is not a published analysis or an investment recommendation.</p>}<blockquote>{note.question}</blockquote>{note.sections.map((section, index) => <section id={`section-${index + 1}`} key={section.heading}><h2>{section.heading}</h2>{section.body ? <RichContent node={section.body.doc} /> : section.paragraphs.map((p) => <p key={p}>{p}</p>)}{section.prompts && <ul className="question-list">{section.prompts.map((prompt) => <li key={prompt}>{prompt}</li>)}</ul>}</section>)}{note.sources.length > 0 && <section className="sources"><h2>Further reading</h2><ul>{note.sources.map((source) => <li key={source.url}><a href={source.url}>{source.title}<ArrowUpRight size={17} aria-hidden="true" /></a></li>)}</ul></section>}{note.download && <a className="button-primary" href={note.download} download>Download research <ArrowDown size={16} aria-hidden="true" /></a>}<div className="article-end"><span className="small-label">{note.status === "sample" ? "EXAMPLE CREATED" : "PUBLISHED"} {formatDate(note.publishedAt)}</span><span aria-hidden="true">✳</span></div></article></div>
    {next && <Link className="next-note" href={`/research/${next.slug}/`}><span className="eyebrow">NEXT IN THE NOTEBOOK</span><span>{next.title}<ArrowUpRight size={32} aria-hidden="true" /></span></Link>}
  </main>;
}
